import { Card } from "../models/generic";

export const deck: Card[] = [
  {
    name: "Ace of Spades",
    img: "http://localhost:3000/imgs/cards/cards/AS.png",
    value: 11,
    isFaceUp: false,
    secondaryValue: 1,
  },
  {
    name: "Two of Spades",
    img: "http://localhost:3000/imgs/cards/cards/2S.png",
    value: 2,
    isFaceUp: false,
  },
  {
    name: "Three of Spades",
    img: "http://localhost:3000/imgs/cards/cards/3S.png",
    value: 3,
    isFaceUp: false,
  },
  {
    name: "Four of Spades",
    img: "http://localhost:3000/imgs/cards/cards/4S.png",
    value: 4,
    isFaceUp: false,
  },
  {
    name: "Five of Spades",
    img: "http://localhost:3000/imgs/cards/cards/5S.png",
    value: 5,
    isFaceUp: false,
  },
  {
    name: "Six of Spades",
    img: "http://localhost:3000/imgs/cards/cards/6S.png",
    value: 6,
    isFaceUp: false,
  },
  {
    name: "Seven of Spades",
    img: "http://localhost:3000/imgs/cards/cards/7S.png",
    value: 7,
    isFaceUp: false,
  },
  {
    name: "Eight of Spades",
    img: "http://localhost:3000/imgs/cards/cards/8S.png",
    value: 8,
    isFaceUp: false,
  },
  {
    name: "Nine of Spades",
    img: "http://localhost:3000/imgs/cards/cards/9S.png",
    value: 9,
    isFaceUp: false,
  },
  {
    name: "Ten of Spades",
    img: "http://localhost:3000/imgs/cards/cards/10S.png",
    value: 10,
    isFaceUp: false,
  },
  {
    name: "Jack of Spades",
    img: "http://localhost:3000/imgs/cards/cards/JS.png",
    value: 10,
    isFaceUp: false,
  },
  {
    name: "Queen of Spades",
    img: "http://localhost:3000/imgs/cards/cards/QS.png",
    value: 10,
    isFaceUp: false,
  },
  {
    name: "King of Spades",
    img: "http://localhost:3000/imgs/cards/cards/KS.png",
    value: 10,
    isFaceUp: false,
  },
  {
    name: "Ace of Hearts",
    img: "http://localhost:3000/imgs/cards/cards/AH.png",
    value: 11,
    isFaceUp: false,
    secondaryValue: 1,
  },
  {
    name: "Two of Hearts",
    img: "http://localhost:3000/imgs/cards/cards/2H.png",
    value: 2,
    isFaceUp: false,
  },
  {
    name: "Three of Hearts",
    img: "http://localhost:3000/imgs/cards/cards/3H.png",
    value: 3,
    isFaceUp: false,
  },
  {
    name: "Four of Hearts",
    img: "http://localhost:3000/imgs/cards/cards/4H.png",
    value: 4,
    isFaceUp: false,
  },
  {
    name: "Five of Hearts",
    img: "http://localhost:3000/imgs/cards/cards/5H.png",
    value: 5,
    isFaceUp: false,
  },
  {
    name: "Six of Hearts",
    img: "http://localhost:3000/imgs/cards/cards/6H.png",
    value: 6,
    isFaceUp: false,
  },
  {
    name: "Seven of Hearts",
    img: "http://localhost:3000/imgs/cards/cards/7H.png",
    value: 7,
    isFaceUp: false,
  },
  {
    name: "Eight of Hearts",
    img: "http://localhost:3000/imgs/cards/cards/8H.png",
    value: 8,
    isFaceUp: false,
  },
  {
    name: "Nine of Hearts",
    img: "http://localhost:3000/imgs/cards/cards/9H.png",
    value: 9,
    isFaceUp: false,
  },
  {
    name: "Ten of Hearts",
    img: "http://localhost:3000/imgs/cards/cards/10H.png",
    value: 10,
    isFaceUp: false,
  },
  {
    name: "Jack of Hearts",
    img: "http://localhost:3000/imgs/cards/cards/JH.png",
    value: 10,
    isFaceUp: false,
  },
  {
    name: "Queen of Hearts",
    img: "http://localhost:3000/imgs/cards/cards/QH.png",
    value: 10,
    isFaceUp: false,
  },
  {
    name: "King of Hearts",
    img: "http://localhost:3000/imgs/cards/cards/KH.png",
    value: 10,
    isFaceUp: false,
  },
  {
    name: "Ace of Diamonds",
    img: "http://localhost:3000/imgs/cards/cards/AD.png",
    value: 11,
    isFaceUp: false,
    secondaryValue: 1,
  },
  {
    name: "Two of Diamonds",
    img: "http://localhost:3000/imgs/cards/cards/2D.png",
    value: 2,
    isFaceUp: false,
  },
  {
    name: "Three of Diamonds",
    img: "http://localhost:3000/imgs/cards/cards/3D.png",
    value: 3,
    isFaceUp: false,
  },
  {
    name: "Four of Diamonds",
    img: "http://localhost:3000/imgs/cards/cards/4D.png",
    value: 4,
    isFaceUp: false,
  },
  {
    name: "Five of Diamonds",
    img: "http://localhost:3000/imgs/cards/cards/5D.png",
    value: 5,
    isFaceUp: false,
  },
  {
    name: "Six of Diamonds",
    img: "http://localhost:3000/imgs/cards/cards/6D.png",
    value: 6,
    isFaceUp: false,
  },
  {
    name: "Seven of Diamonds",
    img: "http://localhost:3000/imgs/cards/cards/7D.png",
    value: 7,
    isFaceUp: false,
  },
  {
    name: "Eight of Diamonds",
    img: "http://localhost:3000/imgs/cards/cards/8D.png",
    value: 8,
    isFaceUp: false,
  },
  {
    name: "Nine of Diamonds",
    img: "http://localhost:3000/imgs/cards/cards/9D.png",
    value: 9,
    isFaceUp: false,
  },
  {
    name: "Ten of Diamonds",
    img: "http://localhost:3000/imgs/cards/cards/10D.png",
    value: 10,
    isFaceUp: false,
  },
  {
    name: "Jack of Diamonds",
    img: "http://localhost:3000/imgs/cards/cards/JD.png",
    value: 10,
    isFaceUp: false,
  },
  {
    name: "Queen of Diamonds",
    img: "http://localhost:3000/imgs/cards/cards/QD.png",
    value: 10,
    isFaceUp: false,
  },
  {
    name: "King of Diamonds",
    img: "http://localhost:3000/imgs/cards/cards/KD.png",
    value: 10,
    isFaceUp: false,
  },
  {
    name: "Ace of Clubs",
    img: "http://localhost:3000/imgs/cards/cards/AC.png",
    value: 11,
    isFaceUp: false,
    secondaryValue: 1,
  },
  {
    name: "Two of Clubs",
    img: "http://localhost:3000/imgs/cards/cards/2C.png",
    value: 2,
    isFaceUp: false,
  },
  {
    name: "Three of Clubs",
    img: "http://localhost:3000/imgs/cards/cards/3C.png",
    value: 3,
    isFaceUp: false,
  },
  {
    name: "Four of Clubs",
    img: "http://localhost:3000/imgs/cards/cards/4C.png",
    value: 4,
    isFaceUp: false,
  },
  {
    name: "Five of Clubs",
    img: "http://localhost:3000/imgs/cards/cards/5C.png",
    value: 5,
    isFaceUp: false,
  },
  {
    name: "Six of Clubs",
    img: "http://localhost:3000/imgs/cards/cards/6C.png",
    value: 6,
    isFaceUp: false,
  },
  {
    name: "Seven of Clubs",
    img: "http://localhost:3000/imgs/cards/cards/7C.png",
    value: 7,
    isFaceUp: false,
  },
  {
    name: "Eight of Clubs",
    img: "http://localhost:3000/imgs/cards/cards/8C.png",
    value: 8,
    isFaceUp: false,
  },
  {
    name: "Nine of Clubs",
    img: "http://localhost:3000/imgs/cards/cards/9C.png",
    value: 9,
    isFaceUp: false,
  },
  {
    name: "Ten of Clubs",
    img: "http://localhost:3000/imgs/cards/cards/10C.png",
    value: 10,
    isFaceUp: false,
  },
  {
    name: "Jack of Clubs",
    img: "http://localhost:3000/imgs/cards/cards/JC.png",
    value: 10,
    isFaceUp: false,
  },
  {
    name: "Queen of Clubs",
    img: "http://localhost:3000/imgs/cards/cards/QC.png",
    value: 10,
    isFaceUp: false,
  },
  {
    name: "King of Clubs",
    img: "http://localhost:3000/imgs/cards/cards/KC.png",
    value: 10,
    isFaceUp: false,
  },
];
